import express from 'express';
import 'dotenv/config';
import cors from 'cors';
import { logger } from './middleware/logger.js';
import { notFoundHandler } from './middleware/notFoundHandler.js';
import { errorHandler } from './middleware/errorHandler.js';
import notesRoutes from './routes/notesRoutes.js';
import { connectMongoDB } from './db/connectMongoDB.js';
import { errors } from 'celebrate';
const app = express();
const PORT = process.env.PORT ?? 3000;
app.use(express.json());
app.use(cors());
app.use(logger);
app.use(notesRoutes);
app.use(errors());
app.use(notFoundHandler);
app.use(errorHandler);
 await connectMongoDB();
app.listen(PORT, () => {
  console.log(`Server is successful running! Server port is ${PORT}.`);
});
